# Generated by Django 4.2 on 2025-06-24 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('MH', 'Maharashtra'), ('GJ', 'Gujarat'), ('DL', 'Delhi'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('UP', 'Uttar Pradesh'), ('RJ', 'Rajasthan'), ('WB', 'West Bengal'), ('KL', 'Kerala'), ('PB', 'Punjab'), ('MP', 'Madhya Pradesh')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
